services:
  backend:
    build: ./reverse-proxy/backend
    expose:
      - "5000"            # lo expone SOLO dentro de Docker
    networks:
      - appnet

  proxy:
    image: nginx:alpine
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"         # abrirá http://localhost:8080
    depends_on:
      - backend
    networks:
      - appnet

  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - "9443:9443"        # UI HTTPS
      # - "9000:9000"      # (opcional) UI HTTP legacy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    networks:
      - appnet


networks:
  appnet:
    driver: bridge

volumes:
  portainer_data:
