events {}

http {
    # 1. ESENCIAL: Define el resolver del DNS interno de Docker (127.0.0.11).
    # 'valid=5s' le dice a NGINX que refresque la lista de IPs cada 5 segundos.
    resolver 127.0.0.11 valid=5s; 
    
    # 2. Define el upstream usando el NOMBRE DEL SERVICIO de Docker Compose.
    # NGINX usará el DNS de Docker (por el 'resolver') para encontrar las IPs de todas las réplicas.
    upstream backend_pool {
        # Usamos el nombre del servicio 'backend' y su puerto
        server backend:5000; 
    }

    server {
        listen 80;

        location / {
            # 3. Usa el nombre del upstream
            proxy_pass http://backend_pool; 
            
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Connection close;
        }
    }
}
   

